import type { Metadata } from "next";
import { Inter,Comfortaa,DM_Serif_Display } from "next/font/google"; import "../globals.css"; import Navbar from "./nav"; import { Toaster } from "@/components/ui/sonner"; import Footer from "./footer";
import { Suspense } from "react";
import Loading from "@/components/Loading";
import LoadingProvider from "@/components/LoadingProvider";
import PixelEvents from "@/components/PixelEvents";

const kanit = DM_Serif_Display({ weight: "400", subsets: ["latin"],variable:"--font-kanit" });


const inter = Inter({ subsets: ["latin"] });
const comfortaa = Comfortaa({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <Navbar />
        <LoadingProvider>
        <div className="min-h-[55vh]">
          {children}

        </div>
        </LoadingProvider>
        <Footer />
        <Toaster />
        <Suspense fallback={null}>
          <PixelEvents />
        </Suspense>
      </body>
    </html>
  );
}
