import type { Metadata } from "next";
import { Inter,Comfortaa } from "next/font/google";
import "../globals.css";
import Navbar from "./nav";
import { Toaster } from "@/components/ui/sonner";
const inter = Inter({ subsets: ["latin"] });
const comfortaa = Comfortaa({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={comfortaa.className}>
        <Navbar />
        {children}
        <Toaster />
      </body>
    </html>
  );
}
