import Nav from "./nav"
import "../globals.css"
import { Comfortaa , Kanit,Inter } from "next/font/google";

const comfortaa = Comfortaa({ subsets: ["latin"] });
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={comfortaa.className}>
        <div className="flex h-screen w-full">
        <Nav />
        <div className="flex-1 overflow-y-auto h-screen">
        {children}
        </div>
        </div>
      </body>
    </html>
  )
}
