import Nav from "./nav"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="h-screen flex ">
        <div className="flex h-full w-full">
        <Nav />
        <div className="flex-1 overflow-y-auto h-screen">
        {children}
        </div>
        </div>
      </body>
    </html>
  )
}
